export default {
  AccessionNumber: 'accessionNumber',
  Age: '',
  ApplyDept: '',
  ApplyDoctor: '',
  ApproveDateTime: '',
  BQ: '',
  BirthDay: 'birthDate',
  CH: '',
  ClinicNo: '',
  DJTime: '',
  Description: '',
  Enhance: '',
  ExposalCount: '',
  FilmCount: '',
  FilmSpec: '',
  Impression: '',
  InhospitalNo: '',
  IsPositive: '',
  JCFS: '',
  Modality: 'modalityType',
  ModalityType: 'modality',
  PatientCName: 'patientName',
  PatientEName: '',
  PatientType: '',
  RISPID: 'patientId',
  Registrar: '',
  RemoteAccNo: '',
  ReportApprover: '',
  ReportApproverImage: '',
  ReportDateTime: '',
  ReportDoctor: '',
  ReportDoctorImage: '',
  ReportFtpURL: '',
  ReportID: '',
  Representation: '',
  Sex: 'gender',
  StudyDateTime: [
    {
      key: 'studyDate',
      type: 'date'
    }, {
      key: 'studyTime',
      type: 'time'
    }
  ],
  Technician: 'technician',
  ZYH: '',
  his_charge: '',
  jc_charge: '',
  status: ''
}
